name: Sync to Google Drive
on: [push]

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: adityak74/google-drive-upload-git-action@main
        with:
          credentials: ${{ secrets.GDRIVE }}
          folderId: 'https://drive.google.com/drive/folders/17n637Gsp4epIpjXK0FuKw7kAaUzW9D0L?usp=drive_link'
          overwrite: "true"
